org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=createterminal
mod_name=Create Terminal
mod_license=MIT
mod_version=1.0.0-1.20.1
mod_group_id=net.chaolux.createterminal
mod_authors=Chaolux
mod_description=Adds a remote terminal to access the Stock Keeper system.